; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:disco_f407vg]
platform = ststm32
board = disco_f407vg
framework = stm32cube

upload_protocol = stlink
debug_tool = stlink

monitor_speed = 115200

build_flags =
    -O2
    -lc -lm -larm_cortexM4lf_math
    -ffast-math
    -fsingle-precision-constant
    --specs=nano.specs
    -fno-strict-aliasing -fno-optimize-sibling-calls
    -Wl,-u,_printf_float    

    -DHSE_VALUE=8000000U
    -DUSE_HAL_DRIVER
    -DSTM32F407xx

    -Ilib/driver
    -Ilib/filter
    -Isrc/Core/Inc
